<a href="https://colab.research.google.com/github/mathewsabu04/Ball-Pong/blob/main/PyTorch_Fundamentals_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

In [1]:
import torch
print(torch.__version__)

2.3.0+cu121


##Introduction To Tensors

Creating Tensors


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#converting back into python int
scalar.item()


7

In [5]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
#Matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.shape

torch.Size([2, 2])

In [9]:
matrix.ndim

2

In [10]:
#Tensor
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
tensor.shape

torch.Size([1, 3, 3])

In [12]:
tensor.ndim

3

## Random Tensors

In [13]:
#Create Random Tensor of size of shape (3,4)
random_tensor = torch.rand(3,4) #rows , col
random_tensor

tensor([[0.0483, 0.9246, 0.0026, 0.8148],
        [0.8024, 0.4828, 0.1585, 0.8566],
        [0.7983, 0.2288, 0.4853, 0.7358]])

In [14]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [15]:
# Create a Tensor of all zeros
zeros = torch.zeros(size=(3,10))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
#Create a range of tensors
one_to_ten = torch.arange(start = 1, end = 1000, step = 22)
one_to_ten

tensor([  1,  23,  45,  67,  89, 111, 133, 155, 177, 199, 221, 243, 265, 287,
        309, 331, 353, 375, 397, 419, 441, 463, 485, 507, 529, 551, 573, 595,
        617, 639, 661, 683, 705, 727, 749, 771, 793, 815, 837, 859, 881, 903,
        925, 947, 969, 991])

## Tensor Data Types

In [17]:
float_tensor = torch.tensor([3.0,6.0,9.0], dtype = None, device = None, requires_grad=False)
float_tensor

tensor([3., 6., 9.])

## Getting information from tensor
1. Tensors not right datatype = to get data type from tensor, use tenor.dtype
2. Tensors not right shape = to get shape tensor.shape
3. Tensors not right device = to get shape tensor.device

In [18]:
#Creating Tensor and add a value to it
tensor = torch.tensor([1,2,3])
tensor = tensor.add(5)
tensor


tensor([6, 7, 8])

In [19]:
#Mulitply
tensor = tensor * 10
tensor

tensor = tensor.mul(10)
tensor

tensor([600, 700, 800])

In [20]:
#Divide
tensor = tensor / 10
tensor

tensor([60., 70., 80.])

In [21]:
#Matrix Mult
torch.matmul(tensor,tensor)

tensor(14900.)

##Finding the min, max, sum

In [22]:
#Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
#Find the min
torch.min(x)

tensor(0)

In [24]:
#Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

## Reshaping, viewing and stacking
1. Reshape - reshapes the input tensor
2. View - Return a view of an input tensor of certain shape
3. Stack - Combine multiple tensors on top of each other

In [25]:
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [26]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [27]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [28]:
# Stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])